"""Initial Migration

Revision ID: 2dbf663ac738
Revises: 0cf3d27cc87b
Create Date: 2019-09-27 10:38:08.687915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbf663ac738'
down_revision = '0cf3d27cc87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('post_review', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('post_title', sa.String(), nullable=True))
    op.drop_column('reviews', 'movie_title')
    op.drop_column('reviews', 'movie_review')
    op.drop_column('reviews', 'movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('movie_review', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('movie_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'post_title')
    op.drop_column('reviews', 'post_review')
    op.drop_column('reviews', 'post_id')
    # ### end Alembic commands ###
