"""Initial Migration

Revision ID: a9b10741b677
Revises: 32ba7bc9aba5
Create Date: 2019-09-28 12:17:03.826513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b10741b677'
down_revision = '32ba7bc9aba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('description', sa.String(length=1000), nullable=True))
    op.drop_column('comments', 'content')
    op.add_column('posts', sa.Column('description', sa.Text(), nullable=False))
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'description')
    op.add_column('comments', sa.Column('content', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('comments', 'description')
    # ### end Alembic commands ###
