"""Initial Migration

Revision ID: b9417269d0b4
Revises: c8209334ca53
Create Date: 2019-09-28 14:42:49.518318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9417269d0b4'
down_revision = 'c8209334ca53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'date_posted')
    op.drop_column('comments', 'date_posted')
    # ### end Alembic commands ###
