"""Initial Migration

Revision ID: c3f348376ae2
Revises: 2dbf663ac738
Create Date: 2019-09-27 10:40:16.895715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f348376ae2'
down_revision = '2dbf663ac738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('posted', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'posted')
    # ### end Alembic commands ###
